# -*- coding: utf-8 -*-
"""My program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eebimiJTzaQuwOUWaJk-QdU82YR6u6zl
"""

def usuario(): #definición: Pide que el usuario ingrese su nombre
    nombre = input("Por favor ingrese su nombre: ") #definición:  la función input( ) en Python funciona para posibilitar la entrada por texto por parte del usuario del programa
    print(f"Hola, {nombre}! Encantado de conocerte.") #definición: f permite ingresar una variable Saludo despues introducir el nombre y conocer a otra persona
    print() #definición: función incorporada que se utiliza para mostrar mensajes en la pantalla.
    print(f"¿En qué te puedo ayudar, {nombre}?") #definición: Ofrece apoyo y da su nombre o lo pide

usuario()